### ISSUE TITLE
Duda bloque entre manos

### ISSUE THREAD

**Issue by dacmail** [politicalwatch/politicalwatch.es#1]
@pr3ssh  una duda sobre el bloque entre manos:

![image](https://user-images.githubusercontent.com/11754/95307676-3d7bd700-0889-11eb-9433-c1f3e70a3528.png)

Lo voy a llamar Featured, y mi duda es si los contenidos que muestra son especificados manualmente o queréis que tire de algun tipo de contenido concreto, supongo que manualmente.

Mi planteamiento será que para insertarlo sea necesario algo así:

`<featured :main="featuredItem" :more="otherItems"></featured>`

Y en el FrontMatter del Markdown tendríais algo así:

```
---
featuredItem:
    - title: 'Vigilancia ciudadana'
    - subtitle: 'Innovamos para fomentar un debate público informado'
    - description: 'Political Watch es la plataforma formada por tecnólogas, economistas y periodistas que se inscribe dentro de la estrategia de CIECODE como una de sus principales líneas de trabajo.'
    - button: 'Saber más'
    - button_link: 'https://....'
---
```

O incluso podríais pasar esos datos directamente al componente sin ponerlo en el frontmatter, en forma de objeto:

`<featured :main="{ title: ...., subtitle: ...., .... }" :more="..."></featured>`
