### ISSUE TITLE
Home completada

### ISSUE THREAD

**Issue by dacmail** [politicalwatch/politicalwatch.es#2]
Buenas Pablo, acabo de terminar la portada, al margen de correción de errores y tal, la estructura no creo que cambie, por si quieres ir metiendo datos reales, probando cómo está, traducciendo al inglés, etc.

Te cuento, para editar la portada, lo puedes hacer con el siguiente archivo Markdown:

https://github.com/politicalwatch/politicalwatch.es/blob/master/content/es/index.md

Creo que tanto el front matter como los componentes se autodefinen mirando ese archivo, pero si necesitas más info me dices. Quizás los únicos comentarios que yo haría a priori son:

* Los datos del `<hero>` están puestos a manopla, es decir, no es un componente reutilizable por que usa cadenas de las traducciones, si queréis que metamos cadenas e imagen como props por mi no hay problema, pero veía este componente bastante cerrado para esos contenidos, por eso lo hice así.
*  Para poder usar el componente `<blog-latest>` que muestra las últimas noticias en el bloque blog, hay que definir previamente en el front matter lo siguiente: `blogLatest: 2`, el número especifica el número de artículos que se mostrarán/ Si no se especifica esta variable en el front matter, el componente padre no hace una precarga de los últimos artículos del blog, por lo tanto el componente `<blog-latest>` no es capaz de mostrar nada.

Lo dicho, si quieres puedes replicar ese archivo Markdown en la versión en inglés para ver cómo funciona: https://github.com/politicalwatch/politicalwatch.es/blob/master/content/en/index.md

Si vas a meterle mano al inglés te recomiendo duplicar también el archivo de idiomas: https://github.com/politicalwatch/politicalwatch.es/blob/master/lang/es-ES.js coge como base el español que es donde yo estoy metiendo todas las cadenas que necesito.

**Comment by pr3ssh** [comment]
Genial. Tiene todo muy buena pinta. Me pongo la próxima semana con ello.

Viéndolo así por encima creo que el bloque

```
sections:
  - title: 'Democracia'
    image: /images/democracy.svg
    subtitle: 'Vigilancia ciudadana para una sociedad mejor'
    button: 'Cuéntame más'
    link: '#link'
  - title: 'Coherencia'
    image: /images/coherence.svg
    subtitle: 'Políticas a la altura de los retos de nuestra era'
    button: 'Cuéntame más'
    link: '#link'
```

lo podemos quitar y meter directamente en un componente llamado **lines-of-work** pero no sé si ese mismo componente **sections** lo usas para otros apartados.
Ya me dices.
